
apiVersion: v1
kind: Service
metadata:
  name: workshop-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: workshop
        image: usmanswa/pokemon-app
        ports:
        - containerPort: 3000
